# -*- coding: utf-8 -*-
"""lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I3ir1TZ6x82H1LaT5rGNwsRzLDWaHuIu
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import PIL.Image

from tensorflow.keras.applications import VGG19
from tensorflow.keras.applications.vgg19 import preprocess_input

from google.colab import files
uploaded = files.upload()

def load_image(path):
    img = tf.io.read_file(path)
    img = tf.image.decode_image(img, channels=3)
    img = tf.image.resize(img, (512,512))
    img = tf.expand_dims(img, axis=0)
    return preprocess_input(img)

content_image = load_image("content.jpg")
style_image = load_image("style.jpg")

vgg = VGG19(include_top=False, weights='imagenet')
vgg.trainable = False

content_layers = ['block5_conv2']

style_layers = [
'block1_conv1',
'block2_conv1',
'block3_conv1',
'block4_conv1',
'block5_conv1'
]

outputs = [vgg.get_layer(name).output for name in style_layers + content_layers]

model = tf.keras.Model([vgg.input], outputs)

def gram_matrix(tensor):
    result = tf.linalg.einsum('bijc,bijd->bcd', tensor, tensor)
    shape = tf.shape(tensor)
    num_locations = tf.cast(shape[1]*shape[2], tf.float32)
    return result / num_locations

def content_loss(base, target):
    return tf.reduce_mean(tf.square(base - target))

def style_loss(base, target):
    return tf.reduce_mean(tf.square(gram_matrix(base) - gram_matrix(target)))

style_targets = model(style_image)[:len(style_layers)]
content_targets = model(content_image)[len(style_layers):]

generated_image = tf.Variable(content_image, dtype=tf.float32)

optimizer = tf.keras.optimizers.Adam(learning_rate=0.02)

@tf.function()
def train_step(image):

    with tf.GradientTape() as tape:

        outputs = model(image)

        style_outputs = outputs[:len(style_layers)]
        content_outputs = outputs[len(style_layers):]

        c_loss = content_loss(content_outputs[0], content_targets[0])

        s_loss = 0

        for s_out, s_target in zip(style_outputs, style_targets):
            s_loss += style_loss(s_out, s_target)

        total_loss = c_loss + 1e4 * s_loss

    grad = tape.gradient(total_loss, image)
    optimizer.apply_gradients([(grad, image)])

for i in range(2000):
    train_step(generated_image)

    if i % 50 == 0:
        print("Step:", i)

result = generated_image.numpy()[0]
result = result - result.min()
result = result / result.max()

plt.imshow(result)
plt.axis('off')